services:
  anjezha-server:
    image: anjezha-server
    build:
      context: .
      dockerfile: dockerFile
    command: npm run dev:start
    ports:
      - "5000:5000"
      # - "5000:3000"
    env_file:
      - ".env.development.local"
    volumes:
      - ./src:/anjezha/src