version: '3'
services:
    anjezha:
      container_name: anjezha-api-container
      image: tahashabaan/anjezha
      ports:
        - "5000:5000"

    web:
      image: nginx
      container_name: anjezha-nginx-container
      restart: always
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        # - ./certbot/conf:/etc/letsencrypt
        # - ./certbot/www:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - anjezha
      environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
    
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/
      depends_on:
        - web
      command: certonly --webroot -w /var/www/certbot --force-renewal --email tahashabaan48@gmail.com -d api.anjez.tech --agree-tos 