# base inage 
FROM node:14.17.0-alpine3.13 AS build

# Create app directory
WORKDIR Anjezha

# copy app dependencies
COPY  package.json .

# install app dependencies
RUN npm install

# copy app source code
COPY . .

# build app 
RUN npm run build

# production environment
EXPOSE 5000

# start app
CMD ["node", "start"]