services:
  anjezha:
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./src:/Anjezha
    build:
      context: .
      dockerfile: dockerFile  # Ensure this path is correct
      target: development
    ports:
      - "3000:5000"
      - "4000:5000"
    command: npm run start:dev