version: '3.8'  # Updated to a more recent version
services:
  anjezha:
    image: tahashabaan/anjezha 
    container_name: anjezha
    restart: always
    ports:
      - "5000:5000"
    # Uncomment the network if needed
    # networks:
    #   - anjezha-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx config
      # - ./certs:/etc/letsencrypt  # Volume for SSL certificates
      # - ./certbot/www:/var/www/certbot  # ACME challenge folder for Let's Encrypt
    depends_on:
      - anjezha

 
# Uncomment if you need a network
# networks:
#   anjezha-network:
#     driver: bridge
