# Base image
FROM node:lts-alpine as base

# Development stage
FROM base as development
WORKDIR /anjezha
COPY package.json ./anjezha
#update npm to latest version
RUN npm install -g npm@10.8.3
RUN npm install
COPY . .
EXPOSE 5000
CMD ["npm", "run", "start:dev"]

# Production stage
FROM base as production
WORKDIR /anjezha
COPY package.json ./
RUN npm install --only=production
COPY . .
RUN npm run build
EXPOSE 5000
CMD ["npm", "run", "start"]