version: '4'
services:
     anjezha:
      # extends:
      #   file: docker-compose.yml
      #   service: Anjezha
  
      environment:
        - NODE_ENV=production
        - PORT=5000
      env_file:
        - .env.production.local
      build: 
        context: .
        target: production
        dockerfile: dockerFile
      ports:
        - "3000:5000"
        - "4000:5000"
      
      command: npm run prod:start
      
      

