# version: '3'
services:
  anjezha:
    image: tahashabaan/anjezha 
    container_name: anjezha
    restart: always
    ports:
      - "5000:5000"
    # networks:
    #   - anjezha-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
      # - ./certbot:/var/www/certbot  # ACME challenge folder for Let's Encrypt
      - ./certs:/etc/letsencrypt  # Volume for SSL certificateset's Encrypt certificates
    depends_on:
      - anjezha
    certbot:
       image: certbot/certbot
       container_name: certbot
       volumes:
        - ./certs:/etc/letsencrypt  # Volume for SSL certificates
        - ./certbot/conf:/etc/letsencrypt/config
        - ./certbot/www:/var/www/certbot
       entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 