version: '3'
services:
    anjezha:
      container_name: anjezha-api-container
      image: tahashabaan/anjezha
      ports:
        - "5000:5000"

    web:
      image: nginx
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      depends_on:
        - anjezha
      environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80