services:
  anjezha:
    env_file: .env  # Correct property name
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./src:/anjezha/src
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:5000"
      - "5000:5000"
      -  4000:5000
    command: npm run prod:start