
version: '4'
services:
  anjezha:
    container_name: anjezha-api-container
    ports:
      - "5000:5000"
    # build: .
    # volumes:
    #   - ./src:/anjezha/src:ro
    # environment:
    # env_file:
    #   - .env.production.local
    

   