services:
  anjezha:
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./src:/anjezha/src
    build:
      context: .
      dockerfile: dockerFile  # Ensure this path is correct
      target: development
    ports:
      - "3000:5000"
      - "4000:5000"
    env_file:
      - .env.development.local
    command: npm run start:dev
  
  # anjezha-db:
  #   image: mongo:latest
  #   restart: always
  #   container_name: anjezha-db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db
  #   env_file:
  #     - .env.development.local
    