# version: '3'
services:
  anjezha:
    image: tahashabaan/anjezha 
    container_name: anjezha
    restart: always
    ports:
      - "5000:5000"
    networks:
      - anjezha-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
      - ./certbot:/var/www/certbot  # ACME challenge folder for Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt  # Let's Encrypt certificates
    depends_on:
      - anjezha
    networks:
      - anjezha-network

networks:
  anjezha-network:
    driver: bridge

