version: '4'
services:
  anjezha:
    container_name: anjezha-api-container
    build:
      context: .
      target: development
   
    ports:
      - "5000:5000"
    
    environment:
      NODE_ENV: development

    env_file:
      - .env.development.local

    command: ["npm", "run", "dev:start"]