# version: '3'
services:
  app:
    image: tahashabaan/anjezha  # Replace with your app's image
    container_name: anjezha
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx config
      - ./certbot:/var/www/certbot  # ACME challenge folder for Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt  # Let's Encrypt certificates
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

