services:
  anjezha:
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./src:/anjezha/src
    build:
      context: .
      dockerfile: dockerFile  # Ensure this path is correct
      target: development
    ports:
      - "3000:5000"
      - "5000:5000"
    command: npm run dev:start #run ts with tsx